global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "slow-api-replicas"
    static_configs:
      - targets:
          - slow-app-monitoring-slow-api-1:8080
          - slow-app-monitoring-slow-api-2:8080
          - slow-app-monitoring-slow-api-3:8080

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
